name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get latest version from ACR
        id: get-version
        run: |
          az acr login --name ${{ vars.ACR_NAME }}
          TAGS=$(az acr repository show-tags \
            --name ${{ vars.ACR_NAME }} \
            --repository ${{ vars.IMAGE_NAME }} \
            --orderby time_desc \
            --output tsv 2>/dev/null || echo "")
          
          if [ -z "$TAGS" ]; then
            LATEST_VERSION=0
          else
            LATEST_VERSION=$(echo "$TAGS" | grep -oP '^v\K[0-9]+$' | sort -n | tail -1)
            if [ -z "$LATEST_VERSION" ]; then
              LATEST_VERSION=0
            fi
          fi
          
          NEW_VERSION=$((LATEST_VERSION + 1))
          echo "version=v${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "Latest version: v${LATEST_VERSION}"
          echo "New version: v${NEW_VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:${{ steps.get-version.outputs.version }}
            ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}

      - name: Deploy using your deployment.yaml
        run: |
          # Replace variables in deployment.yaml using Repository Variables
          sed -i "s|\${ACR_LOGIN_SERVER}|${{ vars.ACR_LOGIN_SERVER }}|g" deployment.yaml
          sed -i "s|\${IMAGE_NAME}|${{ vars.IMAGE_NAME }}|g" deployment.yaml
          sed -i "s|\${VERSION}|${{ steps.get-version.outputs.version }}|g" deployment.yaml
          
          # Apply the deployment
          kubectl apply -f deployment.yaml
          

      - name: Verify deployment
        run: |
          echo "=== Deployment Status ==="
          kubectl get deployment ${{ vars.DEPLOYMENT_NAME }} -n ${{ vars.NAMESPACE }}
          echo ""
          echo "=== Current deployment image ==="
          kubectl get deployment ${{ vars.DEPLOYMENT_NAME }} -n ${{ vars.NAMESPACE }} -o jsonpath='{.spec.template.spec.containers[0].image}'
          echo ""
          echo "=== Pods Status ==="
          kubectl get pods -n ${{ vars.NAMESPACE }} -l app=${{ vars.IMAGE_NAME }}
