name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: pwctask
  ACR_LOGIN_SERVER: pwctask.azurecr.io
  IMAGE_NAME: microservice
  AKS_CLUSTER_NAME: pwctask-aks
  AKS_RESOURCE_GROUP: your-resource-group
  DEPLOYMENT_NAME: Microservices
  NAMESPACE: default

jobs:
  build-push-deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get latest version from ACR
        id: get-version
        run: |
          # Login to ACR
          az acr login --name ${{ env.ACR_NAME }}
          
          # Get all tags and find the highest version number
          TAGS=$(az acr repository show-tags \
            --name ${{ env.ACR_NAME }} \
            --repository ${{ env.IMAGE_NAME }} \
            --orderby time_desc \
            --output tsv 2>/dev/null || echo "")
          
          # Extract version numbers (v1, v2, v3, etc.)
          if [ -z "$TAGS" ]; then
            LATEST_VERSION=0
          else
            LATEST_VERSION=$(echo "$TAGS" | grep -oP '^v\K[0-9]+$' | sort -n | tail -1)
            if [ -z "$LATEST_VERSION" ]; then
              LATEST_VERSION=0
            fi
          fi
          
          # Increment version
          NEW_VERSION=$((LATEST_VERSION + 1))
          echo "version=v${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "Latest version: v${LATEST_VERSION}"
          echo "New version: v${NEW_VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.get-version.outputs.version }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}

 
      - name: Update deployment image
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.IMAGE_NAME }}=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.get-version.outputs.version }} \
            --record
